### ISSUE TITLE
Exception in api.py, line 367 - attempting to get object from string value

### ISSUE THREAD

**Issue by SharperThanThou** [Python-MyQ/Python-MyQ#10]
Operating Environment:
Home Assistant 2023.9.2, Docker Hub (homeassistant/home-assistant)
SynologyDS 220+ DSM 7.2-64570 Update 3

**FIX** - remove .value reference from string object in api.py line 367.  Restart Home assistant. Verified that I can now authenticate and control my opener via HA.

**NOTE / REPRO**: Like many others, the MyQ integration stopped working when the vendor changed their API's.  Like many others, I modified the request.py to include a string value for self._useragent (change from None), which worked temporarily then failed yesterday.  I loaded the 3.1.10 version from this repo, restarted HA and immediately got the error below.  Issue resolved once fix applied.

**Exception / stack trace from Home Assistant Logs:**

Logger: homeassistant.components.myq.config_flow
Source: pymyq/api.py:367
Integration: MyQ (documentation, issues)
First occurred: 2:00:21 PM (1 occurrences)
Last logged: 2:00:21 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/myq/config_flow.py", line 37, in _async_validate_input
    await pymyq.login(username, password, websession, True)
  File "/config/pymyq/api.py", line 610, in login
    await api.authenticate(wait=True)
  File "/config/pymyq/api.py", line 496, in authenticate
    await self._authentication_task
  File "/config/pymyq/api.py", line 509, in _authenticate
    token, expires = await self._oauth_authenticate()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/pymyq/api.py", line 367, in _oauth_authenticate
    data.update({"__RequestVerificationToken": field.get("value").value })
                                               ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'value'

**Comment by saket424** [comment]
I can confirm that the fix suggested by @SharperThanThou worked for me

**Comment by Lash-L** [comment]
This is a known issue that has been fixed led in #9

This was an accidental feature release. I changed computers and forgot to changes branches and that happened.
