### ISSUE TITLE
MyQ authentication fails with 403

### ISSUE THREAD

**Issue by justinlindh** [Python-MyQ/Python-MyQ#19]
The call to refresh oauth token is now failing with the HTTP request returning a 403 (Forbidden).

Example log:
```
2023-10-10 16:32:51.696 ERROR (MainThread) [homeassistant.components.myq] Error fetching myq devices data: Error trying to re-authenticate to myQ service: Error requesting data from https://partner-identity.myq-cloud.com/connect/token: 403 - Forbidden
```

Looks like the call to [authenticate](https://github.com/Python-MyQ/Python-MyQ/blob/f6db6a5903266e2d233c34272b83b81ad2e93e48/pymyq/api.py#L488) is now failing. Likely another barrier/hurdle that MyQ is putting in front of their service.

**Comment by PrplHaz4** [comment]
Are you getting that with the oauth update that was applied to this library today?  It's not unfair to think improper authentication implementation could look a lot like a malicious actor - or thousands of them in the case of the myq addon.

**Comment by justinlindh** [comment]
Yes, I received this error after applying the earlier patch today. I think everybody is receiving this, now. Likely server side changes on Chamberlain's end.

**Comment by CU-Jon** [comment]
I hate being that one to say "+1" since I thumbs-up'd this one, but see my comment in #16. I'm getting the same.

**Comment by BootsSiR** [comment]
On the latest release:

```
Traceback (most recent call last):
  File "/root/xyz/xyz.py", line 40, in updateGarageDoorState
    myq = await pymyq.login(config.USERNAME, config.PASSWORD, websession)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/xyz/.venv/lib/python3.11/site-packages/pymyq/api.py", line 635, in login
    raise err
  File "/root/xyz/.venv/lib/python3.11/site-packages/pymyq/api.py", line 629, in login
    await api.authenticate(wait=True)
  File "/root/xyz/.venv/lib/python3.11/site-packages/pymyq/api.py", line 516, in authenticate
    raise AuthenticationError(str(auth_err)) from auth_err
pymyq.errors.AuthenticationError: Error requesting data from https://partner-identity.myq-cloud.com/connect/token: 403 - Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/xyz/xyz.py", line 119, in <module>
    asyncio.get_event_loop().run_until_complete(mainLoop())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/xyz/xyz.py", line 114, in mainLoop
    success = await updateGarageDoorState()
  File "/root/xyz/xyz.py", line 96, in updateGarageDoorState
    log.error("Error communicating with MyQ", err)
Message: 'Error communicating with MyQ'
Arguments: (AuthenticationError('Error requesting data from https://partner-identity.myq-cloud.com/connect/token: 403 - Forbidden'),)
^CTraceback (most recent call last):
  File "/root/xyz/xyz.py", line 119, in <module>
    asyncio.get_event_loop().run_until_complete(mainLoop())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
(.venv) root@xyz ~/xyz# pip list installed
Package            Version
------------------ ---------
*snip*
python-myq         3.1.12
*snip*
```
